const DEFAULT_MATCH_SCORE = 2;
const DEFAULT_MISMATCH_SCORE = -3;
const DEFAULT_GAP_OPEN_SCORE = -5;
const DEFAULT_GAP_EXTEND_SCORE = -2;
const DEFAULT_WINDOW_PADDING_BP = 80;
const DEFAULT_MAX_CANDIDATE_WINDOWS = 5;
const NEGATIVE_INFINITY_SCORE = -1e15;

const STATE_MATCH = 0;
const STATE_QUERY_GAP = 1;
const STATE_REFERENCE_GAP = 2;

export {
  DEFAULT_GAP_EXTEND_SCORE,
  DEFAULT_GAP_OPEN_SCORE,
  DEFAULT_MATCH_SCORE,
  DEFAULT_MAX_CANDIDATE_WINDOWS,
  DEFAULT_MISMATCH_SCORE,
  DEFAULT_WINDOW_PADDING_BP,
  NEGATIVE_INFINITY_SCORE,
  STATE_MATCH,
  STATE_QUERY_GAP,
  STATE_REFERENCE_GAP
};
