'use strict';

const HIKARI_MCP_TOOL_TIMEOUT_SEC = 300;
const HIKARI_MCP_TOOL_TIMEOUT_MS = HIKARI_MCP_TOOL_TIMEOUT_SEC * 1000;
const HIKARI_MCP_HEADERS_TIMEOUT_MS = HIKARI_MCP_TOOL_TIMEOUT_MS + 5000;
const HIKARI_MCP_KEEP_ALIVE_TIMEOUT_MS = 5000;

module.exports = {
  HIKARI_MCP_TOOL_TIMEOUT_SEC,
  HIKARI_MCP_TOOL_TIMEOUT_MS,
  HIKARI_MCP_HEADERS_TIMEOUT_MS,
  HIKARI_MCP_KEEP_ALIVE_TIMEOUT_MS
};
