'use strict';
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const root=path.resolve(__dirname,'../..');
const storagePath=path.join(root,'TestData3');
const packageRoot=path.join(root,'out/Hikari-darwin-arm64/Hikari.app/Contents/Resources/app.asar');
async function main(){
 if(!process.versions.electron){const result=require('node:child_process').spawnSync(require('electron'),[__filename],{encoding:'utf8',timeout:60000});process.stdout.write(result.stdout||'');process.stderr.write(result.stderr||'');assert.equal(result.status,0,String(result.error||result.signal));return;}
 const {app,BrowserWindow,protocol,ipcMain}=require('electron');
 const previews=require(path.join(packageRoot,'src/main/agent/html-output/preview-service.js'));
 previews.registerHtmlPreviewScheme(protocol);
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'hikari-chat-demos-'));app.setPath('userData',profile);await app.whenReady();
 let win;previews.installHtmlPreviewService({protocol,ipcMain,getMainWindow:()=>win});
 win=new BrowserWindow({width:1150,height:1000,show:false,webPreferences:{preload:path.join(packageRoot,'src/main/preload.js'),contextIsolation:true,nodeIntegration:false,sandbox:false}});
 previews.guardHtmlPreviewNavigation(win.webContents);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));
 const fixture=path.join(profile,'preview.html');const url=file=>pathToFileURL(path.join(packageRoot,file)).href;
 fs.writeFileSync(fixture,`<!doctype html><html><head><meta charset="utf-8"><link rel="stylesheet" href="${url('styles.css')}"><style>body{display:block;padding:1rem;margin:0;background:var(--theme-surface)}#history{max-width:56rem;margin:auto}</style></head><body><main id="history"></main></body></html>`);
 await win.loadFile(fixture);const exec=code=>win.webContents.executeJavaScript(code);
 // Draw synthetic scientific figures, then publish the actual PNG bytes through image_output.
 const images=await exec(`(()=>{const result={};function canvas(){const c=document.createElement('canvas');c.width=1100;c.height=620;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#26374a';x.font='bold 30px system-ui';return[c,x]}let[c,x]=canvas();x.fillText('Illustrative dose response',65,55);x.font='18px system-ui';x.fillText('Synthetic Hill model · EC50 = 3 µM · slope = 2',65,88);x.strokeStyle='#aab5c3';x.lineWidth=2;x.beginPath();x.moveTo(100,135);x.lineTo(100,500);x.lineTo(1030,500);x.stroke();x.font='20px system-ui';for(let i=0;i<=6;i++)x.fillText(String(i*2),95+i*150,535);x.fillText('Concentration (µM)',440,585);for(let i=0;i<=4;i++)x.fillText(String(i*25)+'%',38,505-i*85);x.strokeStyle='#5579df';x.lineWidth=5;x.beginPath();for(let i=0;i<=120;i++){const dose=i/10,r=100*dose*dose/(9+dose*dose);if(i===0)x.moveTo(100,500);else x.lineTo(100+dose*75,500-r*3.4)}x.stroke();result.dose=c.toDataURL('image/png');[c,x]=canvas();x.fillText('Illustrative 96-well plate heatmap',65,55);x.font='18px system-ui';x.fillText('Synthetic response · columns increase; small row offsets',65,88);for(let row=0;row<8;row++){x.fillStyle='#26374a';x.fillText('ABCDEFGH'[row],55,160+row*51);for(let col=0;col<12;col++){const v=(col+1)/12*.85+row/7*.15;x.fillStyle='hsl('+(225-v*180)+',65%,'+(88-v*40)+'%)';x.fillRect(95+col*78,130+row*51,68,40);x.fillStyle='#26374a';x.font='15px system-ui';x.fillText(String(Math.round(v*100)),111+col*78,156+row*51)}}x.font='18px system-ui';for(let col=0;col<12;col++)x.fillText(String(col+1),118+col*78,118);x.fillText('Arbitrary units · demonstration only',65,590);result.plate=c.toDataURL('image/png');[c,x]=canvas();x.fillText('Illustrative group comparison',65,55);x.font='18px system-ui';x.fillText('Synthetic triplicates · mean ± sample SD',65,88);x.strokeStyle='#aab5c3';x.beginPath();x.moveTo(110,135);x.lineTo(110,505);x.lineTo(1020,505);x.stroke();const data=[['Control',11,1],['Low dose',20,2],['High dose',30,2]];data.forEach(([name,m,sd],i)=>{const xx=235+i*300;x.fillStyle=['#96a6bc','#86a6f1','#5579df'][i];x.fillRect(xx-65,505-m*10,130,m*10);x.strokeStyle='#26374a';x.lineWidth=3;x.beginPath();x.moveTo(xx,505-(m+sd)*10);x.lineTo(xx,505-(m-sd)*10);x.moveTo(xx-15,505-(m+sd)*10);x.lineTo(xx+15,505-(m+sd)*10);x.stroke();x.fillStyle='#26374a';x.font='20px system-ui';x.fillText(name,xx-65,545);x.fillText(String(m),xx-12,505-(m+sd)*10-15)});x.font='18px system-ui';x.fillText('Response (arbitrary units)',65,590);result.groups=c.toDataURL('image/png');return result;})()`);
 const assetsPath=path.join(storagePath,'DemoOutputs');fs.mkdirSync(assetsPath,{recursive:true});
 const gateway=require(path.join(packageRoot,'src/main/agent/mcp-contract/gateway.js')).createAgentMcpGateway({storagePath,env:{}});
 const imageArtifacts={};for(const[key,dataUrl]of Object.entries(images)){const file=path.join(assetsPath,key+'.png');fs.writeFileSync(file,Buffer.from(dataUrl.split(',')[1],'base64'));const result=await gateway.callGatewayTool('image_output',{path:file,title:{dose:'Dose-response curve',plate:'Plate heatmap',groups:'Group comparison'}[key],alt:{dose:'Illustrative response rises with concentration; half maximum is at 3 micromolar.',plate:'Illustrative 8 by 12 well grid with response increasing across columns.',groups:'Illustrative means are 11, 20, and 30 arbitrary units, with sample standard deviations 1, 2, and 2.'}[key],caption:'Synthetic demonstration data — not experimental findings.'});assert.equal(result.ok,true);imageArtifacts[key]=result.image_artifact;fs.copyFileSync(file,path.join(__dirname,key+'.png'));}
 const htmlArtifacts={};for(const[key,title]of [['threshold-explorer','Threshold explorer'],['dose-response','Dose-response playground'],['group-comparison','Group comparison explorer']]){const html=fs.readFileSync(path.join(__dirname,key+'.html'),'utf8');const result=await gateway.callGatewayTool('html_output',{title,html,caption:'Illustrative data. Controls affect this preview only; reopening resets them.',height:key==='dose-response'?38:32});assert.equal(result.ok,true);htmlArtifacts[key]=result.html_artifact;}
 const demos=[
 {id:'demo-output-20260912-01',title:'Demo 1 — Image gallery',prompt:'Show me an example of analysis images in chat.',text:'This demo contains two image outputs: a dose-response curve and a plate heatmap. Both use synthetic data solely to demonstrate image display.',meta:{image_artifacts:[imageArtifacts.dose,imageArtifacts.plate]}},
 {id:'demo-output-20260912-02',title:'Demo 2 — Interactive threshold',prompt:'Let me filter samples interactively.',text:'Move the threshold slider to change which illustrative samples remain. Try 0.8: only one of the four samples meets the threshold. Reset restores the initial view.',meta:{html_artifacts:[htmlArtifacts['threshold-explorer']]}},
 {id:'demo-output-20260912-03',title:'Demo 3 — Dose-response playground',prompt:'Help me explore how EC50 and Hill slope change a curve.',text:'Adjust EC50 and Hill slope below. The curve and response at 3 µM update immediately. This is a synthetic mathematical model, not a fitted experiment.',meta:{html_artifacts:[htmlArtifacts['dose-response']]}},
 {id:'demo-output-20260912-04',title:'Demo 4 — Image + interactive report',prompt:'Show a summary figure together with an interactive analysis table.',text:'The static figure shows synthetic group means and sample SD. Use the table below to choose a group or switch to fold change relative to the control mean. High dose is 30 / 11 ≈ 2.73-fold.',meta:{image_artifacts:[imageArtifacts.groups],html_artifacts:[htmlArtifacts['group-comparison']]}}
 ];
 const chat=require(path.join(packageRoot,'src/main/agent/context/agent-chat-log.js')).createAgentChatLogRuntime();
 const indexPath=path.join(storagePath,'chat_log/index.json');const before=JSON.parse(fs.readFileSync(indexPath));const backup=path.join(__dirname,'chat-index-before.json');if(!fs.existsSync(backup))fs.copyFileSync(indexPath,backup);
 for(const demo of demos){const current=await chat.getSession({storagePath,sessionId:demo.id}).catch(()=>null);if(!current?.session){await chat.createSession({storagePath,sessionId:demo.id,title:demo.title});const stamp=new Date().toISOString();await chat.appendRows(storagePath,demo.id,[{type:'user-message',session_id:demo.id,message_id:demo.id+'-user',timestamp:stamp,text:demo.prompt},{type:'assistant-message',session_id:demo.id,message_id:demo.id+'-assistant',timestamp:stamp,text:demo.text,meta:{...demo.meta,demo:true}}]);}
 const loaded=await chat.getSession({storagePath,sessionId:demo.id});assert.equal(loaded.messages.length,2);
 await exec(`(async()=>{const{renderHistory}=await import(${JSON.stringify(url('src/renderer/modules/agent-chat/rendering.js'))});renderHistory({historyNode:document.querySelector('#history'),messages:${JSON.stringify(loaded.messages)},state:{agentChat:{currentSessionId:${JSON.stringify(demo.id)}}},safeText:s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')});await Promise.all([...document.images].map(i=>i.decode()));})()`);
 if(demo.meta.html_artifacts){let frame;for(let i=0;i<100;i++){frame=win.webContents.mainFrame.frames.find(f=>f.url.startsWith('hikari-html:'));if(frame&&await frame.executeJavaScript("Boolean(document.querySelector('#reset'))").catch(()=>false))break;await new Promise(r=>setTimeout(r,20));}assert.ok(frame);if(demo.id.endsWith('02')){await frame.executeJavaScript("document.querySelector('#threshold').value='.8';document.querySelector('#threshold').dispatchEvent(new Event('input'))");assert.equal(await frame.executeJavaScript("document.querySelector('#summary').textContent"),'1 of 4 samples meet the threshold.');}if(demo.id.endsWith('03')){await frame.executeJavaScript("document.querySelector('#ec50').value='6';document.querySelector('#ec50').dispatchEvent(new Event('input'))");assert.equal(await frame.executeJavaScript("document.querySelector('#response').textContent"),'20.0%');}if(demo.id.endsWith('04')){await frame.executeJavaScript("document.querySelector('#group').value='High dose';document.querySelector('#mode').value='fold';document.querySelector('#mode').dispatchEvent(new Event('change'))");assert.equal(await frame.executeJavaScript("document.querySelector('#rows').children.length"),1);assert.equal(await frame.executeJavaScript("document.querySelector('#rows tr').children[2].textContent"),'2.73');}await frame.executeJavaScript("document.querySelector('#reset').click()");}
 fs.writeFileSync(path.join(__dirname,demo.id+'.png'),(await win.webContents.capturePage()).toPNG());console.log('Created and verified: '+demo.title);}
 const after=JSON.parse(fs.readFileSync(indexPath));for(const original of before.sessions){const current=after.sessions.find(s=>s.id===original.id);assert.deepEqual(current,original,'Existing session metadata must remain unchanged');}
 fs.writeFileSync(path.join(__dirname,'manifest.json'),JSON.stringify({storagePath,verifiedWith:packageRoot,demos:demos.map(d=>({id:d.id,title:d.title,log:path.join(storagePath,'chat_log',d.id+'.log')})),existingSessionsPreserved:before.sessions.length},null,2)+'\n');
 win.destroy();fs.rmSync(profile,{recursive:true,force:true});app.quit();
}
main().catch(error=>{console.error(error);if(process.versions.electron)require('electron').app.exit(1);else process.exitCode=1;});
