import { complexityInstructions } from '../complexity.mjs';

// Workflow only: ids, revisions, scratch and inspection. Artwork rules live in
// RENDERER_INSTRUCTIONS; field mechanics live in the request schema.
export const AGENT_INSTRUCTIONS = 'Pin the returned illustration_id on every canvas request; on illustration_changed, list and reopen the intended figure, and never edit a different figure silently. Preserve existing user edits and unrelated objects. Work on main by default; summon scratch with action:"scratch", visible:true only to build intricate components, then transfer or copy them to main and close scratch with visible:false. Apply requires expected_revision and a unique request_id; retry uncertain edits with identical arguments and request_id. Give every component and group a short human-readable name (for example "Mitochondrion" or "ATP export arrow"); the user sees it in the Layers panel. Use component ids for individual rotation and styling, and group ids to move, resize, transfer or delete a set together.\n\nCompletion requires visual inspection. After the last edit, render BOTH canvases (including hidden scratch), and critique them as a demanding reviewer of a textbook figure: compare the render item by item with your brief and the request, and check the depiction, label targets and composition. Fix every problem you can and render again, then call action:"inspect" with expected_revision, the render\'s inspection_id and review:{layout,labels,artwork,science}. The review must name remaining weaknesses, not only confirm requirements. A render alone is not a review; Hikari blocks completion until inspect succeeds for the latest revision in this run.';

export const RENDERER_INSTRUCTIONS = `Artwork: every label must be an independent text object, and all SVG and raster artwork must be text-free.

Figure quality:
- Depict the process the request names, not only its parts: budding shows the membrane curving inward and pinching off; transmembrane proteins cross the whole membrane; arrows follow the real direction of movement or reaction. Add no unrequested decoration, such as cargo dots, extra icons or background shapes.
- Composition: center the content as a whole, filling about 70-85% of the canvas with even margins; align related items and keep spacing consistent.
- Labels: place each label beside its target or connect it with a thin leader line whose end touches the target. A label for several identical items connects to each of them or uses a bracket. Never leave a label whose target is ambiguous.
- Attachments: parts that belong together must touch or overlap, such as a receptor crossing its membrane or a leader line reaching its target. Verify them against object coordinates from read, not only by looking at the render.

Renderer choice, per component:
1. Use SVG by default for schematic geometry: arrows, connectors, panel frames, membranes, simple cells and organelles, receptors, vesicles, DNA cartoons and abstract protein shapes, and anything needing exact counts, positions, topology or later recoloring. Charts, scale bars and atom/bond diagrams must come from known values or verified structure, never generated pixels.
2. Use the Codex-provided built-in image_gen only for a component whose required appearance depends on realistic anatomy, irregular organic surface detail, dense natural texture, complex lighting or photographic style. A biological name alone is not a reason: a schematic mitochondrion is SVG; a realistic textured mitochondrion may be raster. Complexity level and object count never decide the renderer.
3. If unsure, draw one simple SVG draft and render it at final size; switch that component to image_gen only if it is still not recognizable, rather than adding paths round after round. Generate directly when the raster need is clear.
4. Raster pixels cannot be recolored, reshaped or edited individually. Generate only the needed component, never the labeled figure, and keep arrows, boundaries and anything needing independent movement or restyling in separate SVG layers.

Generated component standard:
- One isolated subject, centered and fully in frame with a small margin. Ask for a transparent background; a plain background that matches the canvas is acceptable, so never reject an otherwise good image for its background. No text, labels, arrows, scale bars, borders, ground shadows or watermarks.
- Match the figure: its palette, line weight, lighting direction, viewpoint and the shading the complexity level allows. Prompt image_gen along the lines of: "Isolated <subject>, <flat | lightly shaded | shaded> scientific illustration, palette <hex colors>, transparent background, centered, no text, labels, arrows or shadow."
- Before import, check the image: no baked-in text; correct anatomy, part counts and orientation; nothing invented. Generation cannot establish measured data or exact molecular structure; regenerate or fall back to SVG when it fails.
- Size: do not display a raster larger than its pixel size. A figure holds about 9 MB of images in total, so use few rasters and copy an existing one instead of generating it again.

Import: supply the image as a plugin_canvas asset (source:"codex" for image_gen output) and reference its id as raster_asset in an upsert/update. Image generation must come from Codex: do not configure another provider, request an API key or call an image API from scripts. If image_gen is unavailable or fails, say so and use SVG or user-provided artwork; never silently switch providers.`;

export function agentInstructions(complexity) {
  return `${AGENT_INSTRUCTIONS}\n\nReusable components: read includes reusable_assets and assets_revision, shared across illustrations. Inspect a matching saved component with asset_read/asset_render before reusing it through apply insert_asset. Copies keep separate editable artwork and labels; apply returns inserted_assets with fresh component/group IDs. When asked to save a component for future use, use asset_save with a name and component/group id or component ids, illustration_id, expected_revision, expected_assets_revision and unique request_id. Saving a snapshot leaves the figure unchanged.\n\n${RENDERER_INSTRUCTIONS}\n\n${complexityInstructions(complexity)}`;
}
