import { complexityInstructions, complexityLabel } from '../complexity.mjs';

const ARTWORK_GUIDANCE = 'Prefer SVG. Use image generation for individual components too complex to construct clearly in SVG. Import each as a separate text-free raster layer and assemble it with SVG and independent labels.';

export const AGENT_INSTRUCTIONS = 'Use plugin_canvas with plugin_id:"scientific-illustration". Start with request:{action:"read"} and follow the returned request schema. Pin the returned illustration_id on every read/render/apply/scratch. If the user changes selection, illustration_changed requires listing and reopening the intended figure; never edit a different figure silently. List returns the saved illustration library. Create/open/duplicate require expected_library_revision and a unique request_id. Work directly on main for figures without intricate components. Scratch is hidden by default; summon it only when useful for intricate components using request:{action:"scratch",illustration_id:"ID-from-read",visible:true}. Inspect components, then transfer or copy them to main and close scratch with the same action and visible:false when finished. Hiding preserves its contents and read/render access. Read reports scratch_visible; selection/reload resets visibility. Prefer text-free SVG artwork; every label must be an independent text object. Render canvases to inspect your output and iterate before completion; both can be rendered even while scratch is hidden. Preserve existing user edits and unrelated objects. You can use an available image-generation tool for intricate biological structures, organic forms, textures or realistic details that are too complex to construct clearly in SVG. Generate each needed component separately, with a transparent background when appropriate, and place it as an independent raster object alongside SVG components. Keep arrows, connectors and all labels independently editable; do not flatten the entire figure into one image. If generation is unavailable, explain the limitation and use suitable SVG or user-provided artwork. Inspect raster output visually for baked-in text before importing. Supply files via plugin_canvas assets:[{id:"texture",path:"relative/image.png"}] and reference raster_asset:"texture" in an upsert/update operation with textFree:true. Apply requires expected_revision and a unique request_id. Retry uncertain edits with identical arguments and request_id.';

export function agentInstructions(complexity) {
  return `${AGENT_INSTRUCTIONS}\n\n${complexityInstructions(complexity)} The saved complexity guides visual detail; change it only when the user requests a different level. Scratch is optional below Detailed.`;
}

export function drawingPrompt(illustrationId, complexity, prompt) {
  return `Draw using plugin_canvas with plugin_id:"scientific-illustration". Start with request:{action:"read",illustration_id:"${illustrationId}"} and follow agent_contract. Complexity: ${complexityLabel(complexity)}; follow agent_contract.instructions for this level. Every label must be an independent text object. ${ARTWORK_GUIDANCE}\n\n${prompt}`;
}
