export function getSettingsElements(rootDocument = globalThis?.document || null) {
  const getById = (id) => rootDocument?.getElementById?.(id) || null;
  return {
    settingsNavItems: [...(rootDocument?.querySelectorAll?.('#setting-view [data-settings-target]') || [])],
    settingsPanels: [...(rootDocument?.querySelectorAll?.('#setting-view [data-settings-panel]') || [])],
    appearanceForm: getById('appearance-form'),
    settingFontSize: getById('setting-font-size'),
    settingMode: getById('setting-mode'),
    storageForm: getById('storage-form'),
    settingStoragePath: getById('setting-storage-path'),
    selectStoragePathBtn: getById('select-storage-path-btn'),
    startupForm: getById('startup-form'),
    openLogsFolderBtn: getById('open-logs-folder-btn'),
    openThirdPartyNoticesBtn: getById('open-third-party-notices-btn'),
    settingUpdateStatus: getById('setting-update-status'),
    checkUpdatesBtn: getById('check-updates-btn'),
    installUpdateBtn: getById('install-update-btn'),
    settingStartupDefaultView: getById('setting-startup-default-view'),
    settingStartupRememberLastView: getById('setting-startup-remember-last-view'),
    notebookPdfForm: getById('notebook-pdf-form'),
    settingNotebookPdfPageSize: getById('setting-notebook-pdf-page-size'),
    settingNotebookPdfStapleEdge: getById('setting-notebook-pdf-staple-edge'),
    codexSettingsTabs: [...(rootDocument?.querySelectorAll?.('.settings-codex-tabs [role=tab]') || [])],
    codexSettingsPanels: [getById('codex-hikari-panel'), getById('codex-desktop-panel')].filter(Boolean),
    settingCodexDesktopPreview: getById('setting-codex-desktop-preview'),
    settingCodexDesktopPrompt: getById('setting-codex-desktop-prompt'),
    llmForm: getById('llm-form'),
    settingModel: getById('setting-model'),
    settingReasoningEffort: getById('setting-reasoning-effort'),
    settingCodexAuthControls: getById('setting-codex-auth-controls'),
    settingCodexStatus: getById('setting-codex-status'),
    settingCodexUsage: getById('setting-codex-usage'),
    settingCodexUsageStatus: getById('setting-codex-usage-status'),
    refreshCodexUsageBtn: getById('refresh-codex-usage-btn'),
    settingCodexInstall: getById('setting-codex-install'),
    settingCodexInstallCommand: getById('setting-codex-install-command'),
    settingCodexInstallHelp: getById('setting-codex-install-help'),
    copyCodexInstallCommandBtn: getById('copy-codex-install-command-btn'),
    checkCodexCliBtn: getById('check-codex-cli-btn'),
    startCodexLoginBtn: getById('start-codex-login-btn'),
    clearCodexLoginBtn: getById('clear-codex-login-btn'),
    copyCodexDesktopMcpPromptBtn: getById('copy-codex-desktop-mcp-prompt-btn'),
    settingCodexDesktopMcpStatus: getById('setting-codex-desktop-mcp-status'),
    settingMcpToolsList: getById('setting-mcp-tools-list'),
    settingAgentExternalSkillsEnabled: getById('setting-agent-external-skills-enabled'),
    settingExternalSkillsRefreshBtn: getById('setting-external-skills-refresh-btn'),
    settingExternalSkillsList: getById('setting-external-skills-list'),
    pluginsAddBtn: getById('setting-plugins-add-btn'),
    pluginsReloadBtn: getById('setting-plugins-reload-btn'),
    pluginsStatus: getById('setting-plugins-status'),
    pluginsList: getById('setting-plugins-list'),
    locationInput: getById('setting-location-input'),
    locationAddBtn: getById('setting-location-add-btn'),
    locationList: getById('setting-location-list'),
    sampleInventoryLocationInput: getById('setting-sample-inventory-location-input'),
    sampleInventoryLocationAddBtn: getById('setting-sample-inventory-location-add-btn'),
    sampleInventoryLocationList: getById('setting-sample-inventory-location-list'),
    sampleTypeLabelsForm: getById('sample-type-labels-form'),
    sampleTypeAddInput: getById('setting-sample-type-add-input'),
    sampleTypeAddBtn: getById('setting-sample-type-add-btn'),
    sampleTypeLabelList: getById('setting-sample-type-label-list'),
    preferredJournalForm: getById('preferred-journal-form'),
    settingPreferredJournal: getById('setting-preferred-journal'),
    preferredJournalList: getById('setting-preferred-journal-list'),
    clearPreferredJournalBtn: getById('clear-preferred-journal-btn')
  };
}
