export function getSettingsElements(rootDocument = globalThis?.document || null) {
  const getById = (id) => rootDocument?.getElementById?.(id) || null;
  return {
    settingsNavItems: [...(rootDocument?.querySelectorAll?.('#setting-view [data-settings-target]') || [])],
    settingsPanels: [...(rootDocument?.querySelectorAll?.('#setting-view [data-settings-panel]') || [])],
    appearanceForm: getById('appearance-form'),
    settingFontSize: getById('setting-font-size'),
    settingMode: getById('setting-mode'),
    storageForm: getById('storage-form'),
    settingStoragePath: getById('setting-storage-path'),
    settingStorageImportStatus: getById('setting-storage-import-status'),
    selectStoragePathBtn: getById('select-storage-path-btn'),
    startupForm: getById('startup-form'),
    settingStartupDefaultView: getById('setting-startup-default-view'),
    settingStartupRememberLastView: getById('setting-startup-remember-last-view'),
    llmForm: getById('llm-form'),
    settingProvider: getById('setting-provider'),
    settingModel: getById('setting-model'),
    settingModelOptions: getById('setting-model-options'),
    settingReasoningEffort: getById('setting-reasoning-effort'),
    settingApiEndpoint: getById('setting-api-endpoint'),
    settingApiKey: getById('setting-api-key'),
    settingCodexAuthControls: getById('setting-codex-auth-controls'),
    settingCodexStatus: getById('setting-codex-status'),
    startCodexLoginBtn: getById('start-codex-login-btn'),
    clearCodexLoginBtn: getById('clear-codex-login-btn'),
    settingAgentDeveloperMode: getById('setting-agent-developer-mode'),
    settingAgentExternalSkillsEnabled: getById('setting-agent-external-skills-enabled'),
    settingExternalSkillsStatus: getById('setting-external-skills-status'),
    settingExternalSkillsRefreshBtn: getById('setting-external-skills-refresh-btn'),
    settingExternalSkillsList: getById('setting-external-skills-list'),
    pluginsAddBtn: getById('setting-plugins-add-btn'),
    pluginsReloadBtn: getById('setting-plugins-reload-btn'),
    pluginsStatus: getById('setting-plugins-status'),
    pluginsList: getById('setting-plugins-list'),
    telegramForm: getById('telegram-form'),
    settingTelegramToken: getById('setting-telegram-token'),
    settingTelegramStatus: getById('setting-telegram-status'),
    clearTelegramTokenBtn: getById('clear-telegram-token-btn'),
    locationInput: getById('setting-location-input'),
    locationAddBtn: getById('setting-location-add-btn'),
    locationList: getById('setting-location-list'),
    sampleInventoryLocationInput: getById('setting-sample-inventory-location-input'),
    sampleInventoryLocationAddBtn: getById('setting-sample-inventory-location-add-btn'),
    sampleInventoryLocationList: getById('setting-sample-inventory-location-list'),
    sampleTypeLabelsForm: getById('sample-type-labels-form'),
    sampleTypeLabelList: getById('setting-sample-type-label-list'),
    preferredJournalForm: getById('preferred-journal-form'),
    settingPreferredJournal: getById('setting-preferred-journal'),
    preferredJournalList: getById('setting-preferred-journal-list'),
    clearPreferredJournalBtn: getById('clear-preferred-journal-btn')
  };
}
