export function getSettingsElements(rootDocument = globalThis?.document || null) {
  const getById = (id) => rootDocument?.getElementById?.(id) || null;
  return {
    settingsNavItems: [...(rootDocument?.querySelectorAll?.('#setting-view [data-settings-target]') || [])],
    settingsPanels: [...(rootDocument?.querySelectorAll?.('#setting-view [data-settings-panel]') || [])],
    appearanceForm: getById('appearance-form'),
    settingFontSize: getById('setting-font-size'),
    settingMode: getById('setting-mode'),
    storageForm: getById('storage-form'),
    settingStoragePath: getById('setting-storage-path'),
    selectStoragePathBtn: getById('select-storage-path-btn'),
    startupForm: getById('startup-form'),
    openLogsFolderBtn: getById('open-logs-folder-btn'),
    settingStartupDefaultView: getById('setting-startup-default-view'),
    settingStartupRememberLastView: getById('setting-startup-remember-last-view'),
    notebookPdfForm: getById('notebook-pdf-form'),
    settingNotebookPdfPageSize: getById('setting-notebook-pdf-page-size'),
    settingNotebookPdfStapleEdge: getById('setting-notebook-pdf-staple-edge'),
    llmForm: getById('llm-form'),
    settingModel: getById('setting-model'),
    settingModelOptions: getById('setting-model-options'),
    settingReasoningEffort: getById('setting-reasoning-effort'),
    settingCodexAuthControls: getById('setting-codex-auth-controls'),
    settingCodexStatus: getById('setting-codex-status'),
    startCodexLoginBtn: getById('start-codex-login-btn'),
    clearCodexLoginBtn: getById('clear-codex-login-btn'),
    copyCodexDesktopMcpPromptBtn: getById('copy-codex-desktop-mcp-prompt-btn'),
    settingCodexDesktopMcpStatus: getById('setting-codex-desktop-mcp-status'),
    settingMcpToolsList: getById('setting-mcp-tools-list'),
    settingAgentExternalSkillsEnabled: getById('setting-agent-external-skills-enabled'),
    settingExternalSkillsRefreshBtn: getById('setting-external-skills-refresh-btn'),
    settingExternalSkillsList: getById('setting-external-skills-list'),
    genomesAddBtn: getById('setting-genomes-add-btn'),
    genomesRefreshBtn: getById('setting-genomes-refresh-btn'),
    genomesStatus: getById('setting-genomes-status'),
    genomesList: getById('setting-genomes-list'),
    pluginsAddBtn: getById('setting-plugins-add-btn'),
    pluginsReloadBtn: getById('setting-plugins-reload-btn'),
    pluginsStatus: getById('setting-plugins-status'),
    pluginsList: getById('setting-plugins-list'),
    locationInput: getById('setting-location-input'),
    locationAddBtn: getById('setting-location-add-btn'),
    locationList: getById('setting-location-list'),
    sampleInventoryLocationInput: getById('setting-sample-inventory-location-input'),
    sampleInventoryLocationAddBtn: getById('setting-sample-inventory-location-add-btn'),
    sampleInventoryLocationList: getById('setting-sample-inventory-location-list'),
    sampleTypeLabelsForm: getById('sample-type-labels-form'),
    sampleTypeAddInput: getById('setting-sample-type-add-input'),
    sampleTypeAddBtn: getById('setting-sample-type-add-btn'),
    sampleTypeLabelList: getById('setting-sample-type-label-list'),
    preferredJournalForm: getById('preferred-journal-form'),
    settingPreferredJournal: getById('setting-preferred-journal'),
    preferredJournalList: getById('setting-preferred-journal-list'),
    clearPreferredJournalBtn: getById('clear-preferred-journal-btn')
  };
}
