const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const agent = read('ui/html/views/agent-view.html');
const protocol = read('ui/html/views/protocol-management-view.html');
fs.writeFileSync(path.join(__dirname,'review.html'), String.raw`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Generated draft review comparison</title><link rel="stylesheet" href="../../styles.css"><style>
body{margin:0;background:var(--theme-surface);height:100vh;overflow:hidden}.preview-controls{position:fixed;inset:0 0 auto;display:flex;align-items:center;justify-content:center;gap:.5rem;padding:.75rem;z-index:4000;background:var(--theme-surface);flex-wrap:wrap}.preview-controls button{font-size:.75rem}.app-dialog-overlay.agent-review-overlay{position:fixed;--app-dialog-safe-top:5rem}.app-dialog-overlay{--app-dialog-safe-top:5rem}.preview-caption{position:fixed;bottom:.1rem;left:1rem;font-size:.65rem;color:var(--theme-text-muted);z-index:4000}
@media(max-width:45rem){.app-dialog-overlay,.app-dialog-overlay.agent-review-overlay{--app-dialog-safe-top:7rem}.preview-caption{display:none}}
</style></head><body class="ui-neutral-compact theme-day"><nav class="preview-controls" aria-label="Review examples"><button id="show-agent" class="ghost-btn">Agent Chat</button><button id="show-protocol" class="ghost-btn">Generate Protocol</button><button id="theme" class="ghost-btn">Day / Night</button><button id="reset" class="ghost-btn">Reset samples</button></nav><span class="preview-caption">Sample data · production markup and controllers</span>
<script type="module">
import {createAgentReviewOverlayController} from '../../src/renderer/modules/agent-chat/review-overlay.js';
import {createProtocolPreviewHelpers} from '../../src/renderer/modules/protocol/preview.js';
import {createProtocolGenerationController} from '../../src/renderer/modules/protocol/generation.js';
const mount=(html,id)=>{const t=document.createElement('template');t.innerHTML=html;document.body.append(t.content.querySelector(id));};
mount(${JSON.stringify(agent)},'#agent-review-overlay');
mount(${JSON.stringify(protocol)},'#protocol-generate-result-overlay');
const $=id=>document.getElementById(id);
const safeText=t=>String(t??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const sample={name:'Fluorescence assay preparation',purpose:'Prepare the sample panel and controls for a consistent comparison across the assay plate.',materials:['Sample panel and matched control','Assay plate and plate map','Prepared working buffer','Calibrated pipettes and sterile tips'],steps:[{id:'1',text:'Confirm the sample identifiers and record the plate map before preparing the working solutions.'},{id:'2',text:'Prepare each sample using the approved working dilution. Include the matched negative control and reference sample.'},{id:'3',text:'Transfer the prepared samples to their assigned wells. Keep replicate placement consistent across the panel.'},{id:'4',text:'Record the instrument settings, acquisition time, and any deviations in the notebook.'}],troubleshooting:'Unexpected background: check the matched control and confirm that the correct working buffer was used.\nUneven signal: inspect the plate for bubbles and confirm the recorded sample placement.'};
const draft={proposal:{title:'Fluorescence assay preparation',purpose:sample.purpose,rationale:'Keep sample preparation and the planned readout together in the experiment record.',planned_materials:sample.materials,checkpoints:['Confirm the plate map before acquisition.']},project:{name:'Binding study'},protocol:{name:sample.name},rendered_steps:sample.steps.map(s=>s.text),unresolved_placeholders:[{display:'Select the sample panel before starting.'}],save:{mode:'confirm_before_save'}};
const append={proposal:{proposal_id:'sample-append',page_title:'Fluorescence assay preparation',section_title:'Acquisition notes',content_markdown:'### Before acquisition\nConfirm the **plate map** and record the instrument settings.\n\n- Keep the matched control in view.\n- Note any missing measurements.',sources:[{label:'Experiment plan',detail:'Recorded preparation checklist'}]},save:{mode:'confirm_before_append'}};
const dom={reviewOverlay:$('agent-review-overlay'),reviewTrack:$('agent-review-track'),reviewPageLabel:$('agent-review-page-label'),reviewPrevBtn:$('agent-review-prev-btn'),reviewNextBtn:$('agent-review-next-btn'),reviewCloseBtn:$('agent-review-close-btn')};
window.events=[];window.state={agentChat:{messages:[]},notebookEntries:[]};
window.agent=createAgentReviewOverlayController({dom,state,persist:()=>{},safeText,setStatus:t=>events.push(t),notebookDraftAdapter:{normalizeDraft:d=>d,findEntryForDraft:()=>null},notebookActions:{createPlannedPage:()=>events.push('notebook approved'),rejectPlannedPage:()=>events.push('notebook rejected')},protocolReviewAdapter:{collectReviewProtocols:m=>m.protocols||[],approveGeneratedProtocol:p=>(events.push('protocol approved'),p)},onAppendNotebookEntry:async()=>({ok:true,summary:'append approved'})});
const ui={protocolGenerateResultOverlay:$('protocol-generate-result-overlay'),protocolGenerateResultPreview:$('protocol-generate-result-preview'),protocolGenerateStatus:$('protocol-generate-status'),protocolGenerateApplyBtn:$('protocol-generate-apply-btn'),protocolGeneratePromptInput:{value:'Sample fixture'},protocolNameInput:{focus:()=>{}},protocolPurposeInput:{},protocolMaterialsInput:{},protocolStepsInput:{},protocolTroubleshootingInput:{}};
const helpers=createProtocolPreviewHelpers({safeText,getStepText:s=>s.text,normalizeMaterials:m=>m||[],formatBulletLines:m=>(m||[]).join('\n'),formatStepLines:s=>(s||[]).map(s=>s.text).join('\n')});
const localState={isCreateEditorMode:true,protocolGenerationRequestToken:0,currentProtocolDraft:{}};
window.generation=createProtocolGenerationController({state,ui,localState,safeText,api:{agentGenerateProtocol:async()=>({ok:true,protocol:sample})},cloneDraftFromProtocol:p=>structuredClone(p),sanitizeIncomingProtocol:p=>p,normalizeMaterials:m=>m||[],stepToEditableLine:s=>s.text,...helpers,populateEditorFormFromDraft:d=>helpers.populateEditorFormFromDraft(ui,d),buildDraftFromEditorInputs:()=>({})});
$('protocol-generate-result-close-btn').onclick=()=>generation.closeProtocolGenerateResultOverlay();
$('protocol-generate-back-btn').onclick=()=>generation.closeProtocolGenerateResultOverlay();
$('protocol-generate-apply-btn').onclick=()=>{generation.applyGeneratedProtocolToEditor();events.push('generation applied');};
window.showAgent=()=>{generation.closeProtocolGenerateResultOverlay();agent.close();const m={id:'sample',role:'assistant',meta:{notebookDraft:structuredClone(draft),notebook_append:structuredClone(append),protocols:[sample]}};state.agentChat.messages=[m];agent.openForMessage(m);};
window.showProtocol=async()=>{agent.close();await generation.onGenerateProtocol();};
$('show-agent').onclick=showAgent;$('show-protocol').onclick=showProtocol;$('theme').onclick=()=>{document.body.classList.toggle('theme-night');document.body.classList.toggle('theme-day');};$('reset').onclick=showAgent;showAgent();window.ready=true;
</script></body></html>`);
