'use strict';

const ZIP_EOCD_SIGNATURE = 0x06054b50;
const ZIP_CENTRAL_DIRECTORY_SIGNATURE = 0x02014b50;
const ZIP_LOCAL_FILE_SIGNATURE = 0x04034b50;
const OLE_SIGNATURE = Buffer.from([0xD0, 0xCF, 0x11, 0xE0, 0xA1, 0xB1, 0x1A, 0xE1]);
const FREESECT = 0xFFFFFFFF;
const ENDOFCHAIN = 0xFFFFFFFE;
const FATSECT = 0xFFFFFFFD;
const DIFSECT = 0xFFFFFFFC;

module.exports = {
  DIFSECT,
  ENDOFCHAIN,
  FATSECT,
  FREESECT,
  OLE_SIGNATURE,
  ZIP_CENTRAL_DIRECTORY_SIGNATURE,
  ZIP_EOCD_SIGNATURE,
  ZIP_LOCAL_FILE_SIGNATURE
};
