export function getProtocolDom(documentRef = document) {
  const doc = documentRef;

  return {
    protocolListPanel: doc.getElementById('protocol-list-panel'),
    protocolDetailPanel: doc.getElementById('protocol-detail-panel'),
    protocolEmptyPanel: doc.getElementById('protocol-empty-panel'),
    protocolEditorPanel: doc.getElementById('protocol-editor-panel'),
    protocolViewPanel: doc.getElementById('protocol-view-panel'),
    createProtocolBtn: doc.getElementById('create-protocol-btn'),
    emptyCreateProtocolBtn: doc.querySelector?.('[data-protocol-empty-create]') || null,
    protocolEditorBackBtn: doc.getElementById('protocol-editor-back-btn'),
    protocolCancelBtn: doc.getElementById('protocol-cancel-btn'),
    protocolViewBackBtn: doc.getElementById('protocol-view-back-btn'),
    protocolExportPdfBtn: doc.getElementById('protocol-export-pdf-btn'),
    protocolEditorHeading: doc.getElementById('protocol-editor-heading'),
    protocolViewTitle: doc.getElementById('protocol-view-title'),
    protocolViewContent: doc.getElementById('protocol-view-content'),
    protocolForm: doc.getElementById('protocol-form'),
    protocolJsonImportPanel: doc.getElementById('protocol-json-import-panel'),
    protocolNameInput: doc.getElementById('protocol-name'),
    protocolPurposeInput: doc.getElementById('protocol-purpose'),
    protocolMaterialsInput: doc.getElementById('protocol-materials'),
    protocolStepsInput: doc.getElementById('protocol-steps'),
    protocolTroubleshootingInput: doc.getElementById('protocol-troubleshooting'),
    protocolPolishBtn: doc.getElementById('protocol-polish-btn'),
    protocolPolishOverlay: doc.getElementById('protocol-polish-overlay'),
    protocolPolishCloseBtn: doc.getElementById('protocol-polish-close-btn'),
    protocolPolishKeepEditingBtn: doc.getElementById('protocol-polish-keep-editing-btn'),
    protocolPolishApplyBtn: doc.getElementById('protocol-polish-apply-btn'),
    protocolPolishOriginalPreview: doc.getElementById('protocol-polish-original-preview'),
    protocolPolishResultPreview: doc.getElementById('protocol-polish-result-preview'),
    protocolPolishStatus: doc.getElementById('protocol-polish-status'),
    addPlaceholderBtn: doc.getElementById('add-placeholder-btn'),
    placeholderNameInput: doc.getElementById('placeholder-name'),
    placeholderPresetButtons: [...(doc.querySelectorAll?.('[data-protocol-placeholder-preset]') || [])],
    protocolShareStatus: doc.getElementById('protocol-share-status'),
    protocolShareLinkPanel: doc.getElementById('protocol-share-link-panel'),
    protocolShareLinkOutput: doc.getElementById('protocol-share-link-output'),
    protocolList: doc.getElementById('protocol-list'),
    protocolSortFieldBtn: doc.getElementById('protocol-sort-field-btn'),
    protocolSortOrderBtn: doc.getElementById('protocol-sort-order-btn'),
    protocolJsonImportFileInput: doc.getElementById('protocol-json-import-file'),
    protocolJsonImportInput: doc.getElementById('protocol-json-import-input'),
    importProtocolJsonBtn: doc.getElementById('import-protocol-json-btn'),
    protocolJsonImportStatus: doc.getElementById('protocol-json-import-status')
  };
}
