import { toRepoRelativePath } from './source-scan.mjs';
import { moduleRuntimeFile } from './paths.mjs';

function formatPathList(paths) {
  return paths.map((value) => `\`${value}\``).join(', ');
}

function formatLineList(lines) {
  return lines.map((value) => `L${value}`).join(', ');
}

function buildReport({
  fileDependencyMap,
  directApiCalls,
  wrapperDelegationEdges,
  registeredModules,
  callbackEdges,
  serviceFanOutEdges,
  derivedModuleEdges,
  derivedBridgeEdges,
  directModuleRefEdges
}) {
  const generatedAt = new Date().toISOString();
  const filePaths = Array.from(fileDependencyMap.keys()).sort((left, right) => left.localeCompare(right));
  const importEdgeCount = Array.from(fileDependencyMap.values()).reduce((sum, list) => sum + list.length, 0);
  const reportLines = [
    '# Project Module Relationship Report',
    '',
    '> Auto-generated by `scripts/report-module-relationships.mjs`.',
    '',
    `Generated at: \`${generatedAt}\``,
    '',
    '## Summary',
    '',
    `- Files analyzed: ${filePaths.length}`,
    `- Local import dependency edges: ${importEdgeCount}`,
    `- Direct imported API edges: ${directApiCalls.length}`,
    `- Renderer composition direct API edges: ${wrapperDelegationEdges.length}`,
    `- Registered top-level modules: ${registeredModules.length}`,
    `- Renderer callback wiring edges: ${callbackEdges.length}`,
    `- Service fan-out edges: ${serviceFanOutEdges.length}`,
    `- Derived module-to-module API edges: ${derivedModuleEdges.length}`,
    `- Derived module-to-bridge API edges: ${derivedBridgeEdges.length}`,
    `- Direct module-to-module callback refs: ${directModuleRefEdges.length}`,
    '',
    '## Direct Imported API Communication',
    '',
    '| Caller file | Call expression | Callee file | Relation | Calls | Lines |',
    '| --- | --- | --- | --- | --- | --- |'
  ];

  for (const edge of directApiCalls) {
    reportLines.push(
      `| \`${toRepoRelativePath(edge.callerFile)}\` | \`${edge.callExpression}\` | \`${toRepoRelativePath(edge.calleeFile)}\` | ${edge.relation} | ${edge.callCount} | ${formatLineList(edge.lines)} |`
    );
  }

  reportLines.push(
    '',
    '## Wrapper / Adapter Direct API Communication',
    '',
    '| Wrapper file | Call expression | Internal target | Calls | Lines |',
    '| --- | --- | --- | --- | --- |'
  );

  for (const edge of wrapperDelegationEdges) {
    reportLines.push(
      `| \`${toRepoRelativePath(edge.callerFile)}\` | \`${edge.callExpression}\` | \`${toRepoRelativePath(edge.calleeFile)}\` | ${edge.callCount} | ${formatLineList(edge.lines)} |`
    );
  }

  reportLines.push(
    '',
    '## Registered Top-Level Modules',
    '',
    '| Registry key | Source file |',
    '| --- | --- |'
  );

  for (const moduleRecord of registeredModules) {
    reportLines.push(`| \`${moduleRecord.registryKey}\` | \`${toRepoRelativePath(moduleRecord.sourceFile || moduleRuntimeFile)}\` |`);
  }

  reportLines.push(
    '',
    '## Renderer Callback Wiring',
    '',
    '| Source module | Source file | Callback option | Service method |',
    '| --- | --- | --- | --- |'
  );

  const callbackRows = callbackEdges
    .map((edge) => ({
      ...edge,
      sourceModule: registeredModules.find((entry) => entry.variableName === edge.variableName)?.registryKey || edge.variableName
    }))
    .sort((left, right) => {
      return [
        left.sourceModule,
        left.optionName,
        left.serviceName,
        left.serviceMethod
      ].join(':').localeCompare([
        right.sourceModule,
        right.optionName,
        right.serviceName,
        right.serviceMethod
      ].join(':'));
    });

  for (const edge of callbackRows) {
    reportLines.push(
      `| \`${edge.sourceModule}\` | \`${toRepoRelativePath(edge.sourceFile)}\` | \`${edge.optionName}\` | \`${edge.serviceName}.${edge.serviceMethod}()\` |`
    );
  }

  reportLines.push(
    '',
    '## Service Fan-Out',
    '',
    '| Service method | Target key | Target API | Target type |',
    '| --- | --- | --- | --- |'
  );

  const registeredKeys = new Set(registeredModules.map((entry) => entry.registryKey));
  for (const edge of serviceFanOutEdges) {
    const targetType = registeredKeys.has(edge.targetKey) ? 'module' : 'bridge';
    reportLines.push(
      `| \`${edge.serviceName}.${edge.serviceMethod}()\` | \`${edge.targetKey}\` | \`${edge.targetMethod}()\` | ${targetType} |`
    );
  }

  reportLines.push(
    '',
    '## Derived Module-to-Module API Communication',
    '',
    '| From module | Callback option | Via service | To module | Target API |',
    '| --- | --- | --- | --- | --- |'
  );

  for (const edge of derivedModuleEdges) {
    reportLines.push(
      `| \`${edge.fromRegistryKey}\` | \`${edge.callbackOption}\` | \`${edge.serviceName}.${edge.serviceMethod}()\` | \`${edge.toRegistryKey}\` | \`${edge.targetMethod}()\` |`
    );
  }

  reportLines.push(
    '',
    '## Derived Module-to-Bridge API Communication',
    '',
    '| From module | Callback option | Via service | Bridge target | Target API |',
    '| --- | --- | --- | --- | --- |'
  );

  for (const edge of derivedBridgeEdges) {
    reportLines.push(
      `| \`${edge.fromRegistryKey}\` | \`${edge.callbackOption}\` | \`${edge.serviceName}.${edge.serviceMethod}()\` | \`${edge.targetKey}\` | \`${edge.targetMethod}()\` |`
    );
  }

  reportLines.push(
    '',
    '## Direct Module-to-Module Wiring (callback bodies)',
    '',
    '> Direct cross-module references inside renderer init/options callbacks (`modules.<key>.<method>(...)`).',
    '> These bypass the renderer service layer and indicate tight coupling between modules.',
    '',
    '| From module | From file | To module | Target API |',
    '| --- | --- | --- | --- |'
  );

  for (const edge of directModuleRefEdges) {
    reportLines.push(
      `| \`${edge.fromRegistryKey || edge.variableName}\` | \`${toRepoRelativePath(edge.sourceFile)}\` | \`${edge.targetModuleKey}\` | \`${edge.targetMethod}()\` |`
    );
  }

  reportLines.push(
    '',
    '## Local Import Dependencies',
    ''
  );

  for (const filePath of filePaths) {
    const dependencies = fileDependencyMap.get(filePath) || [];
    if (!dependencies.length) {
      continue;
    }
    reportLines.push(`- \`${filePath}\` -> ${formatPathList(dependencies)}`);
  }

  reportLines.push(
    '',
    '## Notes',
    '',
    '- The dependency section is based on local `import` and `export ... from` statements under `src`.',
    '- The direct imported API section records non-registry calls made through local imports, including explicit public APIs and pure feature modules.',
    '- The renderer-specific API communication sections are inferred from `src/renderer/module-manifests/*.js` callback wiring and `src/renderer/services/*.js` registry fan-out calls.',
    '- Manifest declarations are the preferred registration source. The older inline and legacy `module-runtime.js` forms remain supported for historical reports.',
    '- The "Direct Module-to-Module Wiring" section captures `modules.<key>.<method>(...)` calls inside callback bodies that bypass the renderer service layer.',
    '- Bridge targets are registry entries such as `showView`, `VIEWS`, or `setSearchInputValue` that are not registered app modules.'
  );

  return `${reportLines.join('\n')}\n`;
}

export {
  buildReport
};
