export function getWorkflowElements(rootDocument) {
  return {
    workflowForm: rootDocument?.getElementById?.('workflow-form'),
    workflowIdInput: rootDocument?.getElementById?.('workflow-id'),
    workflowNameInput: rootDocument?.getElementById?.('workflow-name'),
    workflowDescriptionInput: rootDocument?.getElementById?.('workflow-description'),
    workflowProjectInput: rootDocument?.getElementById?.('workflow-project'),
    workflowNotebookPagesInput: rootDocument?.getElementById?.('workflow-notebook-pages'),
    workflowProjectField: rootDocument?.getElementById?.('workflow-project-field'),
    workflowNotebookPagesField: rootDocument?.getElementById?.('workflow-notebook-pages-field'),
    workflowCancelBtn: rootDocument?.getElementById?.('workflow-cancel-btn'),
    workflowBlockTypeInput: rootDocument?.getElementById?.('workflow-block-type'),
    workflowBlockProtocolSearchField: rootDocument?.getElementById?.('workflow-block-protocol-search-field'),
    workflowBlockProtocolField: rootDocument?.getElementById?.('workflow-block-protocol-field'),
    workflowBlockProtocolSearchInput: rootDocument?.getElementById?.('workflow-block-protocol-search'),
    workflowBlockProtocolInput: rootDocument?.getElementById?.('workflow-block-protocol'),
    workflowBlockTextField: rootDocument?.getElementById?.('workflow-block-text-field'),
    workflowBlockTextInput: rootDocument?.getElementById?.('workflow-block-text'),
    workflowBlockAddBtn: rootDocument?.getElementById?.('workflow-block-add-btn'),
    workflowBlockList: rootDocument?.getElementById?.('workflow-block-list'),
    workflowGraphCanvas: rootDocument?.getElementById?.('workflow-graph-canvas'),
    workflowGraphBoard: rootDocument?.getElementById?.('workflow-graph-board'),
    workflowGraphSvg: rootDocument?.getElementById?.('workflow-graph-svg'),
    workflowGraphSelection: rootDocument?.getElementById?.('workflow-graph-selection'),
    workflowGraphNodes: rootDocument?.getElementById?.('workflow-graph-nodes'),
    workflowGraphStatus: rootDocument?.getElementById?.('workflow-graph-status'),
    workflowGraphContextMenu: rootDocument?.getElementById?.('workflow-graph-context-menu'),
    workflowTemplateNameInput: rootDocument?.getElementById?.('workflow-template-name'),
    workflowSaveTemplateBtn: rootDocument?.getElementById?.('workflow-save-template-btn'),
    workflowTemplateList: rootDocument?.getElementById?.('workflow-template-list'),
    workflowSearchInput: rootDocument?.getElementById?.('workflow-search'),
    workflowList: rootDocument?.getElementById?.('workflow-list'),
    workflowExecutionTitle: rootDocument?.getElementById?.('workflow-execution-title'),
    workflowExecutionStatus: rootDocument?.getElementById?.('workflow-execution-status'),
    workflowExecutionBoard: rootDocument?.getElementById?.('workflow-execution-board'),
    workflowAddRunBtn: rootDocument?.getElementById?.('workflow-add-run-btn'),
    workflowDeleteRunBtn: rootDocument?.getElementById?.('workflow-delete-run-btn'),
    workflowSubmitBtn: rootDocument?.querySelector?.('#workflow-form button[type="submit"]'),
    workflowEntryPanel: rootDocument?.getElementById?.('workflow-entry-panel'),
    workflowEntryTemplateBtn: rootDocument?.getElementById?.('workflow-entry-template-btn'),
    workflowEntryViewBtn: rootDocument?.getElementById?.('workflow-entry-view-btn'),
    workflowEntryBackBtn: rootDocument?.getElementById?.('workflow-entry-back-btn'),
    workflowEditorPanels: [...(rootDocument?.querySelectorAll?.('#workflow-management-view .workflow-editor-panel') || [])],
    workflowTemplatePanels: [...(rootDocument?.querySelectorAll?.('#workflow-management-view .workflow-template-panel') || [])],
    workflowListPanels: [...(rootDocument?.querySelectorAll?.('#workflow-management-view .workflow-list-panel') || [])]
  };
}
