const RESTRICTION_STACK_LANE_STEP_PX = 16;
const RESTRICTION_LABEL_COLLISION_GAP_PX = 6;
const RESTRICTION_LABEL_HORIZONTAL_PADDING_PX = 8;

export {
  RESTRICTION_LABEL_COLLISION_GAP_PX,
  RESTRICTION_LABEL_HORIZONTAL_PADDING_PX,
  RESTRICTION_STACK_LANE_STEP_PX
};
