const CODON_USAGE_PROFILES = Object.freeze({
  ecoli: {
    label: 'E. coli (K-12)',
    preferences: {
      F: ['TTC', 'TTT'],
      L: ['CTG', 'TTA', 'TTG', 'CTC', 'CTT', 'CTA'],
      S: ['TCT', 'AGC', 'TCC', 'AGT', 'TCG', 'TCA'],
      Y: ['TAC', 'TAT'],
      '*': ['TAA', 'TGA', 'TAG'],
      C: ['TGC', 'TGT'],
      W: ['TGG'],
      P: ['CCG', 'CCT', 'CCA', 'CCC'],
      H: ['CAC', 'CAT'],
      Q: ['CAG', 'CAA'],
      R: ['CGT', 'CGC', 'CGG', 'AGA', 'AGG', 'CGA'],
      I: ['ATT', 'ATC', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACT', 'ACA', 'ACG'],
      N: ['AAC', 'AAT'],
      K: ['AAA', 'AAG'],
      V: ['GTG', 'GTT', 'GTC', 'GTA'],
      A: ['GCG', 'GCC', 'GCT', 'GCA'],
      D: ['GAT', 'GAC'],
      E: ['GAA', 'GAG'],
      G: ['GGC', 'GGT', 'GGG', 'GGA']
    }
  },
  human: {
    label: 'Human (H. sapiens)',
    preferences: {
      F: ['TTC', 'TTT'],
      L: ['CTG', 'CTC', 'TTG', 'CTT', 'TTA', 'CTA'],
      S: ['AGC', 'TCC', 'TCT', 'AGT', 'TCA', 'TCG'],
      Y: ['TAC', 'TAT'],
      '*': ['TGA', 'TAA', 'TAG'],
      C: ['TGC', 'TGT'],
      W: ['TGG'],
      P: ['CCC', 'CCG', 'CCA', 'CCT'],
      H: ['CAC', 'CAT'],
      Q: ['CAG', 'CAA'],
      R: ['CGC', 'AGA', 'CGG', 'AGG', 'CGT', 'CGA'],
      I: ['ATC', 'ATT', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACA', 'ACT', 'ACG'],
      N: ['AAC', 'AAT'],
      K: ['AAG', 'AAA'],
      V: ['GTG', 'GTC', 'GTT', 'GTA'],
      A: ['GCC', 'GCT', 'GCA', 'GCG'],
      D: ['GAC', 'GAT'],
      E: ['GAG', 'GAA'],
      G: ['GGC', 'GGG', 'GGA', 'GGT']
    }
  },
  mouse: {
    label: 'Mouse (M. musculus)',
    preferences: {
      F: ['TTC', 'TTT'],
      L: ['CTG', 'CTC', 'TTG', 'CTT', 'TTA', 'CTA'],
      S: ['AGC', 'TCC', 'TCT', 'AGT', 'TCA', 'TCG'],
      Y: ['TAC', 'TAT'],
      '*': ['TGA', 'TAA', 'TAG'],
      C: ['TGC', 'TGT'],
      W: ['TGG'],
      P: ['CCC', 'CCT', 'CCA', 'CCG'],
      H: ['CAC', 'CAT'],
      Q: ['CAG', 'CAA'],
      R: ['AGA', 'CGC', 'AGG', 'CGG', 'CGT', 'CGA'],
      I: ['ATC', 'ATT', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACA', 'ACT', 'ACG'],
      N: ['AAC', 'AAT'],
      K: ['AAG', 'AAA'],
      V: ['GTG', 'GTC', 'GTT', 'GTA'],
      A: ['GCC', 'GCT', 'GCA', 'GCG'],
      D: ['GAC', 'GAT'],
      E: ['GAG', 'GAA'],
      G: ['GGC', 'GGA', 'GGG', 'GGT']
    }
  },
  rat: {
    label: 'Rat (R. norvegicus)',
    preferences: {
      F: ['TTC', 'TTT'],
      L: ['CTG', 'CTC', 'TTG', 'CTT', 'TTA', 'CTA'],
      S: ['TCC', 'AGC', 'TCT', 'AGT', 'TCA', 'TCG'],
      Y: ['TAC', 'TAT'],
      '*': ['TGA', 'TAA', 'TAG'],
      C: ['TGC', 'TGT'],
      W: ['TGG'],
      P: ['CCC', 'CCT', 'CCA', 'CCG'],
      H: ['CAC', 'CAT'],
      Q: ['CAG', 'CAA'],
      R: ['AGA', 'CGC', 'AGG', 'CGG', 'CGT', 'CGA'],
      I: ['ATC', 'ATT', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACA', 'ACT', 'ACG'],
      N: ['AAC', 'AAT'],
      K: ['AAG', 'AAA'],
      V: ['GTG', 'GTC', 'GTT', 'GTA'],
      A: ['GCC', 'GCT', 'GCA', 'GCG'],
      D: ['GAC', 'GAT'],
      E: ['GAG', 'GAA'],
      G: ['GGC', 'GGA', 'GGG', 'GGT']
    }
  },
  yeast: {
    label: 'Yeast (S. cerevisiae)',
    preferences: {
      F: ['TTT', 'TTC'],
      L: ['TTG', 'TTA', 'CTT', 'CTA', 'CTG', 'CTC'],
      S: ['TCT', 'TCA', 'AGT', 'TCC', 'AGC', 'TCG'],
      Y: ['TAT', 'TAC'],
      '*': ['TAA', 'TAG', 'TGA'],
      C: ['TGT', 'TGC'],
      W: ['TGG'],
      P: ['CCT', 'CCA', 'CCC', 'CCG'],
      H: ['CAT', 'CAC'],
      Q: ['CAA', 'CAG'],
      R: ['AGA', 'AGG', 'CGT', 'CGC', 'CGA', 'CGG'],
      I: ['ATT', 'ATA', 'ATC'],
      M: ['ATG'],
      T: ['ACT', 'ACA', 'ACC', 'ACG'],
      N: ['AAT', 'AAC'],
      K: ['AAA', 'AAG'],
      V: ['GTT', 'GTA', 'GTG', 'GTC'],
      A: ['GCT', 'GCA', 'GCC', 'GCG'],
      D: ['GAT', 'GAC'],
      E: ['GAA', 'GAG'],
      G: ['GGT', 'GGA', 'GGC', 'GGG']
    }
  },
  bacillus: {
    label: 'B. subtilis',
    preferences: {
      F: ['TTT', 'TTC'],
      L: ['TTA', 'TTG', 'CTT', 'CTA', 'CTG', 'CTC'],
      S: ['TCT', 'TCA', 'AGT', 'TCC', 'AGC', 'TCG'],
      Y: ['TAT', 'TAC'],
      '*': ['TAA', 'TGA', 'TAG'],
      C: ['TGT', 'TGC'],
      W: ['TGG'],
      P: ['CCA', 'CCT', 'CCC', 'CCG'],
      H: ['CAT', 'CAC'],
      Q: ['CAA', 'CAG'],
      R: ['AGA', 'CGT', 'AGG', 'CGC', 'CGA', 'CGG'],
      I: ['ATT', 'ATA', 'ATC'],
      M: ['ATG'],
      T: ['ACA', 'ACT', 'ACC', 'ACG'],
      N: ['AAT', 'AAC'],
      K: ['AAA', 'AAG'],
      V: ['GTA', 'GTT', 'GTC', 'GTG'],
      A: ['GCA', 'GCT', 'GCC', 'GCG'],
      D: ['GAT', 'GAC'],
      E: ['GAA', 'GAG'],
      G: ['GGA', 'GGT', 'GGC', 'GGG']
    }
  },
  pichia: {
    label: 'K. phaffii (Pichia pastoris)',
    preferences: {
      F: ['TTT', 'TTC'],
      L: ['CTG', 'TTG', 'CTT', 'TTA', 'CTA', 'CTC'],
      S: ['TCT', 'AGT', 'TCC', 'TCA', 'AGC', 'TCG'],
      Y: ['TAT', 'TAC'],
      '*': ['TAA', 'TAG', 'TGA'],
      C: ['TGT', 'TGC'],
      W: ['TGG'],
      P: ['CCA', 'CCT', 'CCC', 'CCG'],
      H: ['CAT', 'CAC'],
      Q: ['CAA', 'CAG'],
      R: ['AGA', 'CGT', 'AGG', 'CGC', 'CGA', 'CGG'],
      I: ['ATT', 'ATC', 'ATA'],
      M: ['ATG'],
      T: ['ACA', 'ACT', 'ACC', 'ACG'],
      N: ['AAT', 'AAC'],
      K: ['AAA', 'AAG'],
      V: ['GTT', 'GTG', 'GTA', 'GTC'],
      A: ['GCT', 'GCA', 'GCC', 'GCG'],
      D: ['GAT', 'GAC'],
      E: ['GAA', 'GAG'],
      G: ['GGT', 'GGA', 'GGC', 'GGG']
    }
  },
  arabidopsis: {
    label: 'Arabidopsis (A. thaliana)',
    preferences: {
      F: ['TTT', 'TTC'],
      L: ['CTT', 'TTA', 'TTG', 'CTG', 'CTA', 'CTC'],
      S: ['TCT', 'AGT', 'TCC', 'TCA', 'AGC', 'TCG'],
      Y: ['TAT', 'TAC'],
      '*': ['TAA', 'TGA', 'TAG'],
      C: ['TGT', 'TGC'],
      W: ['TGG'],
      P: ['CCA', 'CCT', 'CCC', 'CCG'],
      H: ['CAT', 'CAC'],
      Q: ['CAA', 'CAG'],
      R: ['AGA', 'AGG', 'CGT', 'CGC', 'CGA', 'CGG'],
      I: ['ATT', 'ATC', 'ATA'],
      M: ['ATG'],
      T: ['ACA', 'ACT', 'ACC', 'ACG'],
      N: ['AAT', 'AAC'],
      K: ['AAA', 'AAG'],
      V: ['GTT', 'GTA', 'GTG', 'GTC'],
      A: ['GCT', 'GCA', 'GCC', 'GCG'],
      D: ['GAT', 'GAC'],
      E: ['GAA', 'GAG'],
      G: ['GGT', 'GGA', 'GGC', 'GGG']
    }
  },
  drosophila: {
    label: 'Drosophila (D. melanogaster)',
    preferences: {
      F: ['TTC', 'TTT'],
      L: ['CTG', 'CTC', 'TTG', 'CTT', 'TTA', 'CTA'],
      S: ['TCC', 'AGC', 'TCT', 'AGT', 'TCG', 'TCA'],
      Y: ['TAC', 'TAT'],
      '*': ['TGA', 'TAA', 'TAG'],
      C: ['TGC', 'TGT'],
      W: ['TGG'],
      P: ['CCC', 'CCA', 'CCT', 'CCG'],
      H: ['CAC', 'CAT'],
      Q: ['CAG', 'CAA'],
      R: ['CGC', 'CGG', 'AGA', 'AGG', 'CGT', 'CGA'],
      I: ['ATC', 'ATT', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACA', 'ACT', 'ACG'],
      N: ['AAC', 'AAT'],
      K: ['AAG', 'AAA'],
      V: ['GTG', 'GTC', 'GTT', 'GTA'],
      A: ['GCC', 'GCT', 'GCA', 'GCG'],
      D: ['GAC', 'GAT'],
      E: ['GAG', 'GAA'],
      G: ['GGC', 'GGG', 'GGA', 'GGT']
    }
  },
  c_elegans: {
    label: 'C. elegans',
    preferences: {
      F: ['TTT', 'TTC'],
      L: ['CTT', 'TTA', 'TTG', 'CTA', 'CTG', 'CTC'],
      S: ['TCT', 'AGT', 'TCA', 'TCC', 'AGC', 'TCG'],
      Y: ['TAT', 'TAC'],
      '*': ['TAA', 'TGA', 'TAG'],
      C: ['TGT', 'TGC'],
      W: ['TGG'],
      P: ['CCA', 'CCT', 'CCC', 'CCG'],
      H: ['CAT', 'CAC'],
      Q: ['CAA', 'CAG'],
      R: ['AGA', 'AGG', 'CGT', 'CGC', 'CGA', 'CGG'],
      I: ['ATT', 'ATA', 'ATC'],
      M: ['ATG'],
      T: ['ACA', 'ACT', 'ACC', 'ACG'],
      N: ['AAT', 'AAC'],
      K: ['AAA', 'AAG'],
      V: ['GTT', 'GTA', 'GTG', 'GTC'],
      A: ['GCT', 'GCA', 'GCC', 'GCG'],
      D: ['GAT', 'GAC'],
      E: ['GAA', 'GAG'],
      G: ['GGT', 'GGA', 'GGC', 'GGG']
    }
  },
  zebrafish: {
    label: 'Zebrafish (D. rerio)',
    preferences: {
      F: ['TTC', 'TTT'],
      L: ['CTG', 'TTG', 'CTC', 'CTT', 'TTA', 'CTA'],
      S: ['AGC', 'TCC', 'TCT', 'AGT', 'TCG', 'TCA'],
      Y: ['TAC', 'TAT'],
      '*': ['TGA', 'TAA', 'TAG'],
      C: ['TGC', 'TGT'],
      W: ['TGG'],
      P: ['CCC', 'CCA', 'CCT', 'CCG'],
      H: ['CAC', 'CAT'],
      Q: ['CAG', 'CAA'],
      R: ['AGA', 'CGC', 'AGG', 'CGG', 'CGT', 'CGA'],
      I: ['ATC', 'ATT', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACA', 'ACT', 'ACG'],
      N: ['AAC', 'AAT'],
      K: ['AAG', 'AAA'],
      V: ['GTG', 'GTC', 'GTT', 'GTA'],
      A: ['GCC', 'GCT', 'GCA', 'GCG'],
      D: ['GAC', 'GAT'],
      E: ['GAG', 'GAA'],
      G: ['GGC', 'GGA', 'GGG', 'GGT']
    }
  },
  pseudomonas: {
    label: 'P. aeruginosa',
    preferences: {
      F: ['TTC', 'TTT'],
      L: ['CTG', 'CTC', 'CTT', 'TTG', 'TTA', 'CTA'],
      S: ['TCC', 'AGC', 'TCG', 'TCT', 'AGT', 'TCA'],
      Y: ['TAC', 'TAT'],
      '*': ['TGA', 'TAA', 'TAG'],
      C: ['TGC', 'TGT'],
      W: ['TGG'],
      P: ['CCG', 'CCC', 'CCT', 'CCA'],
      H: ['CAC', 'CAT'],
      Q: ['CAG', 'CAA'],
      R: ['CGC', 'CGG', 'CGT', 'CGA', 'AGG', 'AGA'],
      I: ['ATC', 'ATT', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACG', 'ACT', 'ACA'],
      N: ['AAC', 'AAT'],
      K: ['AAG', 'AAA'],
      V: ['GTG', 'GTC', 'GTT', 'GTA'],
      A: ['GCC', 'GCG', 'GCT', 'GCA'],
      D: ['GAC', 'GAT'],
      E: ['GAG', 'GAA'],
      G: ['GGC', 'GGG', 'GGT', 'GGA']
    }
  },
  salmonella: {
    label: 'S. enterica',
    preferences: {
      F: ['TTT', 'TTC'],
      L: ['CTG', 'TTA', 'TTG', 'CTT', 'CTC', 'CTA'],
      S: ['TCT', 'TCC', 'AGC', 'AGT', 'TCA', 'TCG'],
      Y: ['TAT', 'TAC'],
      '*': ['TAA', 'TGA', 'TAG'],
      C: ['TGT', 'TGC'],
      W: ['TGG'],
      P: ['CCG', 'CCA', 'CCT', 'CCC'],
      H: ['CAT', 'CAC'],
      Q: ['CAG', 'CAA'],
      R: ['CGT', 'CGC', 'CGG', 'AGA', 'AGG', 'CGA'],
      I: ['ATT', 'ATC', 'ATA'],
      M: ['ATG'],
      T: ['ACC', 'ACT', 'ACA', 'ACG'],
      N: ['AAT', 'AAC'],
      K: ['AAA', 'AAG'],
      V: ['GTG', 'GTT', 'GTC', 'GTA'],
      A: ['GCG', 'GCC', 'GCT', 'GCA'],
      D: ['GAT', 'GAC'],
      E: ['GAA', 'GAG'],
      G: ['GGC', 'GGT', 'GGG', 'GGA']
    }
  }
});

export {
  CODON_USAGE_PROFILES
};
